"""Constant definitions for the site."""

from typing import Dict, List, Union

CATEGORIES: Dict[str, str] = {
    "shade": "Shading",
    "loop": "Loop / Path",
    "region": "Region division",
    "num": "Number",
    "var": "Variety",
    "draw": "Drawing",
}


PUZZLE_TYPES: Dict[str, Dict[str, Union[str, List[str]]]] = {
    "aqre": {
        "name": "Aqre",
        "cat": "shade",
        "aliases": [],
        "examples": [
            "m=edit&p=7VZdb9pKEH3nV0R+3gfvro0/3tKU9CWlNyVVFFkoMsRJUAxODdxURvz3nNkdxza4urq6qporVcD6+Hh25szsjpf1921aZkK69NWhwBUfT4bmp8Kh+bn8uVps8iw+EafbzWNRAgjx5fxc3Kf5OhskbDUd7Koori5F9SlOHOkIR+EnnamoLuNd9TmuRqKa4JEjJLgLa6QARw28Ns8JnVlSusBjxoA3gPNFOc+z2wvL/BUn1ZVwKM4HM5ugsyz+zhzWQffzYjlbEDFLN0hm/bh45ifr7V3xtGVbOd2L6tTKnfTI1Y1cglYuoR65lMUvlhtN93uU/SsE38YJaf/WwLCBk3iHcRzvHO3S1BBa7No42idCt4iwrgUTviZi2BCBIsJriMhYYLlrQkrvwETaOC0v0jeB3mZBoDQyb8x4bkZlxitkISptxo9mdM3om/HC2IyQnPK1UD5CK2w+3wNGUIN94KHFnmqwwl73kA1hCXsFSYQj2EdsE6EXooBxAMw2IexrHLjolzou7ANUGVjrQGiqJ2HldbGy2rSUXSxZTxS+Ya0joWkZauyxfw/N60nGmMu54Ap7q1+rYWNPWNlctNRvWEXwKa1/g122d+Hftf5ViFxaWIV1HaDT5bgu4kqOKxGLdpvRTDptfXCFNq4D2chaD/zLmqfcI64t6lzHIhzwmgZYo4DXKKCacy5DrEXAa0F4yJo9aG5jj31q+Gxj2qhmP8An68cVmOdqCcxrpLGXNNdNRg2mvRHWOmHfxtQ9BmNuwPY+5tbYo73KuRP2OEeKZTA2+7XZ8mdm9Mw4NK0QULv/qxfCf++6f5SToHp0unQ//v+Pmw4SZ7It79N5hpfx6O4hOxkX5TLNcTfeLmdZWd/jLHTWRX67ZuvYHJV4eYNbGcsOlRfFc75Yde0WD6uizHofEZkhfI/9rCjvDry/pHneIezh36HsGdWhNiUOoNZ9WpbFS4dZppvHDtE6rDqestWmK2CTdiWmT+lBtGWT837g/HDML9H0J+XPH43f9EeDlsB9b2+X9ybH7N6i7G190D3dD7a3y5k/anTwRy1NAY+7GmxPY4M97G1Qx+0N8qjDwf2kycnrYZ+TqsNWp1BH3U6h2g2fTAev"
        ],
    },
    "aquarium": {"name": "Aquarium", "cat": "shade", "aliases": [], "examples": []},
    "balance": {"name": "Balance Loop", "cat": "loop", "aliases": ["balanceloop"], "examples": []},
    "battleship": {"name": "Battleship", "cat": "var", "aliases": [], "examples": []},
    "binairo": {"name": "Binairo", "cat": "shade", "aliases": [], "examples": []},
    "box": {"name": "Box", "cat": "shade", "aliases": [], "examples": []},
    "canal": {"name": "Canal View", "cat": "shade", "aliases": ["canalview"], "examples": []},
    "castle": {"name": "Castle Wall", "cat": "loop", "aliases": ["castlewall"], "examples": []},
    "cave": {"name": "Cave (Corral)", "cat": "shade", "aliases": [], "examples": []},
    "chocona": {"name": "Chocona", "cat": "shade", "aliases": [], "examples": []},
    "country": {"name": "Country Road", "cat": "loop", "aliases": ["countryroad"], "examples": []},
    "doppelblock": {"name": "Doppelblock", "cat": "num", "aliases": [], "examples": []},
    "easyas": {"name": "Easy As", "cat": "num", "aliases": [], "examples": []},
    "fillomino": {"name": "Fillomino", "cat": "num", "aliases": [], "examples": []},
    "gokigen": {"name": "Gokigen (Slant)", "cat": "draw", "aliases": [], "examples": []},
    "haisu": {"name": "Haisu", "cat": "loop", "aliases": [], "examples": []},
    "hashi": {"name": "Hashiwokakero (Bridges)", "cat": "loop", "aliases": ["bridges"], "examples": []},
    "heteromino": {"name": "Heteromino", "cat": "region", "aliases": [], "examples": []},
    "heyawake": {"name": "Heyawake", "cat": "shade", "aliases": [], "examples": []},
    "hitori": {"name": "Hitori", "cat": "shade", "aliases": [], "examples": []},
    "hotaru": {"name": "Hotaru Beam", "cat": "loop", "aliases": [], "examples": []},
    "jousan": {"name": "Jousan", "cat": "draw", "aliases": [], "examples": []},
    "kakuro": {"name": "Kakuro", "cat": "num", "aliases": [], "examples": []},
    "kurotto": {"name": "Kurotto", "cat": "shade", "aliases": [], "examples": []},
    "kurodoko": {"name": "Kurodoko", "cat": "shade", "aliases": [], "examples": []},
    "lits": {"name": "LITS", "cat": "shade", "aliases": [], "examples": []},
    "lightup": {"name": "Light Up (Akari)", "cat": "var", "aliases": ["akari"], "examples": []},
    "magnets": {"name": "Magnets", "cat": "var", "aliases": [], "examples": []},
    "masyu": {"name": "Masyu", "cat": "loop", "aliases": [], "examples": []},
    "mines": {"name": "Minesweeper", "cat": "var", "aliases": ["minesweeper"], "examples": []},
    "moonsun": {"name": "Moon-or-Sun", "cat": "loop", "aliases": [], "examples": []},
    "nagare": {"name": "Nagareru-Loop", "cat": "loop", "aliases": ["nagareru"], "examples": []},
    "nanro": {"name": "Nanro", "cat": "num", "aliases": [], "examples": []},
    "ncells": {"name": "N Cells", "cat": "region", "aliases": ["fivecells", "fourcells"], "examples": []},
    "nonogram": {"name": "Nonogram", "cat": "shade", "aliases": [], "examples": []},
    "norinori": {"name": "Norinori", "cat": "shade", "aliases": [], "examples": []},
    "numlin": {"name": "Numberlink", "cat": "loop", "aliases": ["numberlink"], "examples": []},
    "nuribou": {"name": "Nuribou", "cat": "shade", "aliases": [], "examples": []},
    "nurikabe": {"name": "Nurikabe", "cat": "shade", "aliases": [], "examples": []},
    "nurimisaki": {"name": "Nurimisaki", "cat": "shade", "aliases": [], "examples": []},
    "onsen": {"name": "Onsen-Meguri", "cat": "loop", "aliases": [], "examples": []},
    "ripple": {"name": "Ripple Effect", "cat": "num", "aliases": ["rippleeffect"], "examples": []},
    "shakashaka": {"name": "Shakashaka", "cat": "var", "aliases": [], "examples": []},
    "shikaku": {"name": "Shikaku", "cat": "region", "aliases": [], "examples": []},
    "shimaguni": {"name": "Shimaguni (Islands)", "cat": "shade", "aliases": ["islands"], "examples": []},
    "simpleloop": {"name": "Simple Loop", "cat": "loop", "aliases": [], "examples": []},
    "skyscrapers": {"name": "Skyscrapers", "cat": "num", "aliases": [], "examples": []},
    "slither": {"name": "Slitherlink", "cat": "loop", "aliases": ["slitherlink"], "examples": []},
    "spiralgalaxies": {"name": "Spiral Galaxies", "cat": "region", "aliases": [], "examples": []},
    "starbattle": {"name": "Star Battle", "cat": "var", "aliases": [], "examples": []},
    "statuepark": {"name": "Statue Park", "cat": "var", "aliases": [], "examples": []},
    "stostone": {"name": "Stostone", "cat": "shade", "aliases": [], "examples": []},
    "sudoku": {"name": "Sudoku", "cat": "num", "aliases": [], "examples": []},
    "tapa": {"name": "Tapa", "cat": "shade", "aliases": [], "examples": []},
    "tasquare": {"name": "Tasquare", "cat": "shade", "aliases": [], "examples": []},
    "tatamibari": {"name": "Tatamibari", "cat": "region", "aliases": [], "examples": []},
    "tents": {"name": "Tents", "cat": "var", "aliases": [], "examples": []},
    "tapaloop": {
        "name": "Tapa-Like Loop",
        "cat": "loop",
        "aliases": ["tapalikeloop", "tapa-like-loop", "tapalike", "tapa-like"],
        "examples": [],
    },
    "yajilin": {"name": "Yajilin", "cat": "loop", "aliases": [], "examples": []},
    "yajikazu": {"name": "Yajisan-Kazusan", "cat": "shade", "aliases": ["yk", "yajisan-kazusan"], "examples": []},
    "yinyang": {"name": "Yin-Yang", "cat": "shade", "aliases": [], "examples": []},
}

# pylint: skip-file
