"""Constant definitions for the site."""

from typing import Dict, List, Union

CATEGORIES: Dict[str, str] = {
    "shade": "Shading",
    "loop": "Loop / Path",
    "region": "Region division",
    "num": "Number",
    "var": "Variety",
    "draw": "Drawing",
}


PUZZLE_TYPES: Dict[str, Dict[str, Union[str, List[str]]]] = {
    "aqre": {
        "name": "Aqre",
        "cat": "shade",
        "aliases": [],
        "examples": [
            "m=edit&p=7VZdb+O2En33r1joWUBFUrI+3tJs0j4kbvc6RbAwjECxubGwsuXSdrdQkP++Z0YjS7JdFMVF0S1Q2KIOj4Yzh0OOqN2vh9xZXwX0N4mPO36hSvjSyZivQH4Pxb602Tv/6rBfVQ7A93+6vfU/5eXOjmZiNR+91mlWf/DrH7KZpzzf07iUN/frD9lrfZ/VE7+e4pHnK3B3jZEGvOngIz8ndN2QKgCeCAb8CLgo3KK0T3cN83M2qx98j+J8z6MJeuvqN+uJDuovqvVzQcRzvsdkdqtiK092h2X1+SC2av7m11eN3OkFuaaTS7CRS+iCXJrF3yw3nb+9Ie3/g+CnbEbaf+lg0sFp9op2kr16JqChCbQ0a+OZiAjTI5I2F0JEhohxR8SaiLAjUrbAcreEUuGJiWri9LyoiAMdR0GgYpkfub3lVnP7gFn4teH2PbcBtxG3d2xzg8npyPg6QmiNzReFwAjKOAIeNzjUHdbY6yFmQ1jBXkMS4RT2qdikqIU0FhwDi00C+xbHAeqljQv7GFkGNib2DeWTsA6HWDfajFJDrERPmhyxMalvaBlaHIr/EMUbKsEYK3PBHfaNfqPHnT1h3czFKHPEOoVP1fhnHIh9AP9B418nmEsP66TNA3QGEjdAXCVxFWLRbmPNpLPJD+7QJnkgG9XqgX/V8jT3VHKLPLexCMeypjHWKJY1iinnMpcx1iKWtSA8Fs0hNPdxKD4NfPYxbVTeD/Ap+nEHlrFGAcsaGewlI3lTaYdpbyStTtj3MVUPY4yNxT7C2BaHtFdl7oRDmSPFYozN/shb/prbkNsxl0JM5f6XXgj/f9X9qZwZskeny/AX/fu4+WjmTQ/uU76weBnfFRv7blK5dV62vfdF/lJtuv6ts0fL+2K5LI+9H225tQ69m+VLzwv3el64L14YD8fduHxHjx7zkqwnh/WzdZ036ePgaeF9B6eA1/lmWSzzvd11vPoOb+2jUbEk/1M+czrH0r+u3IbFtH272Tu2X+Vbvm/touARDyvr1lVneuVc9YUUVOtttSv21sPng7eryqedJDjjrwucd+A2rGZAlVW1LZHJAVm8bCpnLz4i0iJnF+yfK7c88f6FEtonmu+lAdUc6wNq73Bm9/o5z7LPrPP9akD0zveBJ6RyKGCfDyXmn/OTaOtuzm8j73ePr5mh77r/vs3+oW8zWoLgW3shf2tyePdW7mLpg75Q/WAvVrnwZ4UO/qykKeB5VYO9UNhgT2sb1Hl5gzyrcHB/UOTk9bTOSdVpqVOos2qnUP2Cn81HXwE="
        ],
    },
    "aquarium": {"name": "Aquarium", "cat": "shade", "aliases": [], "examples": []},
    "balance": {"name": "Balance Loop", "cat": "loop", "aliases": ["balanceloop"], "examples": []},
    "battleship": {"name": "Battleship", "cat": "var", "aliases": [], "examples": []},
    "binairo": {"name": "Binairo", "cat": "shade", "aliases": [], "examples": []},
    "box": {"name": "Box", "cat": "shade", "aliases": [], "examples": []},
    "canal": {"name": "Canal View", "cat": "shade", "aliases": ["canalview"], "examples": []},
    "castle": {"name": "Castle Wall", "cat": "loop", "aliases": ["castlewall"], "examples": []},
    "cave": {"name": "Cave (Corral)", "cat": "shade", "aliases": [], "examples": []},
    "chocona": {"name": "Chocona", "cat": "shade", "aliases": [], "examples": []},
    "country": {"name": "Country Road", "cat": "loop", "aliases": ["countryroad"], "examples": []},
    "doppelblock": {"name": "Doppelblock", "cat": "num", "aliases": [], "examples": []},
    "easyas": {"name": "Easy As", "cat": "num", "aliases": [], "examples": []},
    "fillomino": {"name": "Fillomino", "cat": "num", "aliases": [], "examples": []},
    "gokigen": {"name": "Gokigen (Slant)", "cat": "draw", "aliases": [], "examples": []},
    "haisu": {"name": "Haisu", "cat": "loop", "aliases": [], "examples": []},
    "hashi": {"name": "Hashiwokakero (Bridges)", "cat": "loop", "aliases": ["bridges"], "examples": []},
    "heteromino": {"name": "Heteromino", "cat": "region", "aliases": [], "examples": []},
    "heyawake": {"name": "Heyawake", "cat": "shade", "aliases": [], "examples": []},
    "hitori": {"name": "Hitori", "cat": "shade", "aliases": [], "examples": []},
    "hotaru": {"name": "Hotaru Beam", "cat": "loop", "aliases": [], "examples": []},
    "jousan": {"name": "Jousan", "cat": "draw", "aliases": [], "examples": []},
    "kakuro": {"name": "Kakuro", "cat": "num", "aliases": [], "examples": []},
    "kurotto": {"name": "Kurotto", "cat": "shade", "aliases": [], "examples": []},
    "kurodoko": {"name": "Kurodoko", "cat": "shade", "aliases": [], "examples": []},
    "lits": {"name": "LITS", "cat": "shade", "aliases": [], "examples": []},
    "lightup": {"name": "Light Up (Akari)", "cat": "var", "aliases": ["akari"], "examples": []},
    "magnets": {"name": "Magnets", "cat": "var", "aliases": [], "examples": []},
    "masyu": {"name": "Masyu", "cat": "loop", "aliases": [], "examples": []},
    "mines": {"name": "Minesweeper", "cat": "var", "aliases": ["minesweeper"], "examples": []},
    "moonsun": {"name": "Moon-or-Sun", "cat": "loop", "aliases": [], "examples": []},
    "nagare": {"name": "Nagareru-Loop", "cat": "loop", "aliases": ["nagareru"], "examples": []},
    "nanro": {"name": "Nanro", "cat": "num", "aliases": [], "examples": []},
    "ncells": {"name": "N Cells", "cat": "region", "aliases": ["fivecells", "fourcells"], "examples": []},
    "nonogram": {"name": "Nonogram", "cat": "shade", "aliases": [], "examples": []},
    "norinori": {"name": "Norinori", "cat": "shade", "aliases": [], "examples": []},
    "numlin": {"name": "Numberlink", "cat": "loop", "aliases": ["numberlink"], "examples": []},
    "nuribou": {"name": "Nuribou", "cat": "shade", "aliases": [], "examples": []},
    "nurikabe": {"name": "Nurikabe", "cat": "shade", "aliases": [], "examples": []},
    "nurimisaki": {"name": "Nurimisaki", "cat": "shade", "aliases": [], "examples": []},
    "onsen": {"name": "Onsen-Meguri", "cat": "loop", "aliases": [], "examples": []},
    "ripple": {"name": "Ripple Effect", "cat": "num", "aliases": ["rippleeffect"], "examples": []},
    "shakashaka": {"name": "Shakashaka", "cat": "var", "aliases": [], "examples": []},
    "shikaku": {"name": "Shikaku", "cat": "region", "aliases": [], "examples": []},
    "shimaguni": {"name": "Shimaguni (Islands)", "cat": "shade", "aliases": ["islands"], "examples": []},
    "simpleloop": {"name": "Simple Loop", "cat": "loop", "aliases": [], "examples": []},
    "skyscrapers": {"name": "Skyscrapers", "cat": "num", "aliases": [], "examples": []},
    "slither": {"name": "Slitherlink", "cat": "loop", "aliases": ["slitherlink"], "examples": []},
    "spiralgalaxies": {"name": "Spiral Galaxies", "cat": "region", "aliases": [], "examples": []},
    "starbattle": {"name": "Star Battle", "cat": "var", "aliases": [], "examples": []},
    "statuepark": {"name": "Statue Park", "cat": "var", "aliases": [], "examples": []},
    "stostone": {"name": "Stostone", "cat": "shade", "aliases": [], "examples": []},
    "sudoku": {"name": "Sudoku", "cat": "num", "aliases": [], "examples": []},
    "tapa": {"name": "Tapa", "cat": "shade", "aliases": [], "examples": []},
    "tasquare": {"name": "Tasquare", "cat": "shade", "aliases": [], "examples": []},
    "tatamibari": {"name": "Tatamibari", "cat": "region", "aliases": [], "examples": []},
    "tents": {"name": "Tents", "cat": "var", "aliases": [], "examples": []},
    "tapaloop": {
        "name": "Tapa-Like Loop",
        "cat": "loop",
        "aliases": ["tapalikeloop", "tapa-like-loop", "tapalike", "tapa-like"],
        "examples": [],
    },
    "yajilin": {"name": "Yajilin", "cat": "loop", "aliases": [], "examples": []},
    "yajikazu": {"name": "Yajisan-Kazusan", "cat": "shade", "aliases": ["yk", "yajisan-kazusan"], "examples": []},
    "yinyang": {"name": "Yin-Yang", "cat": "shade", "aliases": [], "examples": []},
}

# pylint: skip-file
