"""The [Clingo](https://potassco.org/clingo/) backend that generates solutions for the given ASP problem."""

import logging
import time
from typing import Any, Dict, List

from clingo.control import Control
from clingo.core import MessageCode
from clingo.solving import Model

from noqx.manager import generate_program, prepare_puzzle, store_solution


def clingo_logging_handler(code: MessageCode, message: str) -> None:  # pragma: no cover
    """A wrapper to handle [Clingo](https://potassco.org/clingo/) logging.

    * If the [Clingo](https://potassco.org/clingo/) message code is `RuntimeError`, it will
    be logged as an error.

    * Otherwise, it will be logged as a warning. All the error messages will be stripped.

    Args:
        code: The [Clingo](https://potassco.org/clingo/) message code.
        message: The [Clingo](https://potassco.org/clingo/) message.
    """
    if code == MessageCode.RuntimeError:
        logging.error(f"[Clingo] {code.name}: {message.strip()}")
    else:
        logging.warning(f"[Clingo] {code.name}: {message.strip()}")


class Config:
    """Configurations for the [Clingo](https://potassco.org/clingo/) solver.

    * These configurations will be transferred to the solver instance,
    and users can modify them by specific commands before running the solver.

    Attributes:
        time_limit: The time limit (in seconds) for solving a puzzle (default = 30).
        max_solutions_to_find: The maximum number of solutions to find (default = 10).
        parallel_threads: The number of parallel threads to use for solving (default = 1).
    """

    time_limit: int = 30
    max_solutions_to_find: int = 10
    parallel_threads: int = 1


class ClingoSolver:
    """The [Clingo](https://potassco.org/clingo/) solver backend."""

    def __init__(self):
        """Initialize a solver instance and a model container."""
        self.clingo_instance: Control = Control(logger=clingo_logging_handler)
        self.model: List[str] = []

    def store_model(self, model: Model):  # pragma: no cover
        """A wrapper to store the model on solving and convert the `Model` object to `str`.

        Args:
            model: The model generated by the [Clingo](https://potassco.org/clingo/) solver itself.
        """
        self.model.append(str(model))

    def solve(self, program: str):
        """Solve the ASP problem.

        * The solver instance configurations can be modified by the settings from `Config` class.

        Args:
            program: The ASP program to be solved.
        """
        self.clingo_instance.configuration.sat_prepro = 2
        self.clingo_instance.configuration.asp.trans_ext = "dynamic"  # type: ignore
        self.clingo_instance.configuration.asp.eq = 1  # type: ignore
        self.clingo_instance.configuration.solve.parallel_mode = Config.parallel_threads  # type: ignore
        self.clingo_instance.configuration.solve.models = Config.max_solutions_to_find  # type: ignore
        self.clingo_instance.add(program=program)
        self.clingo_instance.ground()
        with self.clingo_instance.solve(on_model=self.store_model, async_=True) as handle:  # type: ignore
            handle.wait(Config.time_limit)
            handle.cancel()

    def solution(self) -> List[str]:
        """Get the solutions from the model container."""
        return self.model


def run_solver(puzzle_name: str, puzzle_content: str, param: Dict[str, Any]) -> Dict[str, List[str]]:
    """Run the solver and get the list of converted [Penpa+](https://swaroopg92.github.io/penpa-edit/) solution URLs.

    * This is a connector for the [Clingo](https://potassco.org/clingo/) solver, the puzzle, and the solutions. The connector prepares the puzzle, generates the program, runs the solver, and stores the solutions in a sequence. The solution time is also recorded for performance analysis.

    Args:
        puzzle_name: The name of the puzzle.
        puzzle_content: The puzzle content exported in [Penpa+](https://swaroopg92.github.io/penpa-edit/) format.
        param: Additional parameters for the puzzle.

    Raises:
        TimeoutError: If the solving process exceeds the time limit defined in `Config.time_limit`.
    """
    start = time.perf_counter()  # start the counter
    puzzle = prepare_puzzle(puzzle_name, puzzle_content, param)
    logging.debug(f"[Solver] {str(puzzle_name).capitalize()} board unpacked.")

    program = generate_program(puzzle)

    instance = ClingoSolver()
    instance.solve(program)

    solutions: List[str] = []
    for solution in instance.solution():
        solution = store_solution(puzzle, solution)
        solutions.append(solution.encode())
        logging.debug(f"[Solver] {str(puzzle_name).capitalize()} board packed.")

    stop = time.perf_counter()  # stop the counter

    if (stop - start) >= Config.time_limit:
        logging.warning(f"[Solver] {str(puzzle_name).capitalize()} puzzle timed out.")
        raise TimeoutError("Time limit exceeded.")

    logging.info(f"[Solver] {str(puzzle_name).capitalize()} puzzle solved.")
    logging.info(f"[Stats] {str(puzzle_name).capitalize()} solver took {stop - start} seconds.")

    return {"url": solutions}
